name: "Insights Core Labeler"
on:
- pull_request_target

jobs:
  triage:
    if: github.repository == 'RedHatInsights/insights-core'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"